#!/bin/bash

STATE_SHAPEFILE=tl_2022_us_state/tl_2022_us_state.shp
STATE_TABLE=states

COUNTY_SHAPEFILE=tl_2022_us_county/tl_2022_us_county.shp
COUNTY_TABLE=counties

PG_HOST=db
PG_PORT=5432
PG_DBNAME=playground
PG_USER=itme

OGR_TRUNCATE=YES
OGR_LAYER_OVERWRITE=YES
TO_CRS=EPSG:4326
PG_USE_COPY=YES
FEATURES_PER_TRANSACTION=10000

psql --host $PG_HOST --port $PG_PORT --user $PG_USER $PG_DBNAME <<EOF
DROP TABLE IF EXISTS $STATE_TABLE CASCADE;
EOF

echo "Inserting $STATE_SHAPEFILE into $STATE_TABLE"
ogr2ogr -f "PostgreSQL" \
	PG:"host=$PG_HOST port=$PG_PORT user=$PG_USER dbname=$PG_DBNAME" \
	-nlt PROMOTE_TO_MULTI \
	$STATE_SHAPEFILE \
	-nln $STATE_TABLE \
	-t_SRS $TO_CRS \
	-lco OVERWRITE=$OGR_LAYER_OVERWRITE \
	--config OGR_TRUNCATE $OGR_TRUNCATE \
	--config PG_USE_COPY $PG_USE_COPY \
	-gt $FEATURES_PER_TRANSACTION \
	-overwrite

echo "Inserting $COUNTY_SHAPEFILE into $COUNTY_TABLE"
ogr2ogr -f "PostgreSQL" \
	PG:"host=$PG_HOST port=$PG_PORT user=$PG_USER dbname=$PG_DBNAME" \
	-nlt PROMOTE_TO_MULTI \
	$COUNTY_SHAPEFILE \
	-nln $COUNTY_TABLE \
	-t_SRS $TO_CRS \
	-lco OVERWRITE=$OGR_LAYER_OVERWRITE \
	--config OGR_TRUNCATE $OGR_TRUNCATE \
	--config PG_USE_COPY $PG_USE_COPY \
	-gt $FEATURES_PER_TRANSACTION \
	-overwrite

