name: Docker Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose Up
        run: docker-compose -f docker-compose.yml up
      - name: Run psql
        run: docker-compose exec main bash -c "psql --version"

